name: Update Exercism stats in README

on:
  workflow_call:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}

      - name: Make script executable
        run: chmod +x .github/scripts/update-exercism-stats.sh

      - name: Run update script
        env:
          GIT_AUTHOR_NAME: "Mathieu Prot"
          GIT_AUTHOR_EMAIL: "62431571+Rockvald@users.noreply.github.com"
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        run: ./.github/scripts/update-exercism-stats.sh -p
